# Generated by Django 2.2.4 on 2019-09-25 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(null=True)),
                ('start_year', models.DateField(null=True)),
                ('end_year', models.DateField(null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_in_edup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('liked', 'liked'), ('registered', 'registered')], max_length=30)),
                ('isActive', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_in_course', to='HTQL.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.FloatField()),
                ('accumutation', models.IntegerField()),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studyprogram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_in_study', to='HTQL.StudyProgram')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('program_id', models.ManyToManyField(related_name='sub_in_program', to='HTQL.EduProgram')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_in_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('studyprogram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_in_study', to='HTQL.StudyProgram')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTQL.Subject')),
                ('transcript_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_in_transcript', to='HTQL.Transcript')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('room', models.CharField(max_length=6, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_in_course', to='HTQL.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTQL.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_in_program', to='HTQL.EduProgram'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='HTQL.Subject'),
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(null=True)),
                ('score', models.FloatField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_in_course', to='HTQL.Course')),
                ('studyprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_in_stup', to='HTQL.StudyProgram')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTQL.Subject')),
            ],
        ),
    ]
