# Generated by Django 2.2.4 on 2019-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0003_auto_20190925_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
