# Generated by Django 2.2.4 on 2019-09-25 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0005_auto_20190925_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='eduprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpt_in_edup', to='HTQL.EduProgram'),
        ),
        migrations.AlterField(
            model_name='department',
            name='teacher',
            field=models.ManyToManyField(related_name='dpt_in_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
