# Generated by Django 2.2.4 on 2019-10-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0006_auto_20190925_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='GPA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='accumutation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='studyprogram_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_in_study', to='HTQL.StudyProgram'),
        ),
    ]
