# Generated by Django 2.2.4 on 2019-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0007_auto_20191001_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_score',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
