# Generated by Django 2.2.4 on 2019-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTQL', '0008_sub_score_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub_score',
            name='score',
            field=models.FloatField(default=None),
        ),
    ]
